CREATE DATABASE IF NOT EXISTS Employees;

USE Employees;
CREATE TABLE IF NOT EXISTS Department_Table(DepartmentID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(100));
CREATE TABLE IF NOT EXISTS Employee_Table(EmployeeID INT AUTO_INCREMENT PRIMARY KEY, DepartmentID INT NOT NULL, EmployeeName VARCHAR(150) NOT NULL, Salary DECIMAL(10,2), FOREIGN KEY(DepartmentID) REFERENCES Department_Table(DepartmentID));
