DROP DATABASE IF EXISTS LearningManagementSystem;
CREATE DATABASE IF NOT EXISTS LearningManagementSystem;

USE LearningManagementSystem;

DROP TABLE IF EXISTS Students;
CREATE TABLE IF NOT EXISTS Students(StudentID INT AUTO_INCREMENT PRIMARY KEY,StudentAge INT NOT NULL,StudentName VARCHAR(150) NOT NULL,StudentEmail VARCHAR(150) UNIQUE,Courses VARCHAR(100));

DROP TABLE IF EXISTS Instructors;
CREATE TABLE IF NOT EXISTS Instructors(InstructorID INT AUTO_INCREMENT PRIMARY KEY,InstructorAge INT NOT NULL,InstructorName VARCHAR(150) NOT NULL,InstructorEmail VARCHAR(150) UNIQUE, Courses VARCHAR(150));

DROP TABLE IF EXISTS Courses;

CREATE TABLE IF NOT EXISTS Courses(CourseID INT AUTO_INCREMENT PRIMARY KEY,CourseName VARCHAR(150) NOT NULL, CourseInstructor VARCHAR(150));
