CREATE DATABASE IF NOT EXISTS library_db;

USE library_db;

CREATE TABLE IF NOT EXISTS Books(BookID INT AUTO_INCREMENT PRIMARY KEY, isbn VARCHAR(13) NOT NULL, BookTitle VARCHAR(100) NOT NULL, BookAuthor VARCHAR(100) NOT NULL, Quantity INT NOT NULL);
CREATE TABLE IF NOT EXISTS Members(Member_id INT AUTO_INCREMENT PRIMARY KEY, MemberName VARCHAR(100));
