# Generated by Django 5.1 on 2024-08-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'second_name', 'surname', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'isbn', 'publication_year')},
        ),
    ]
